### ISSUE TITLE
Quick search with `:` symbol raise an error

### ISSUE THREAD

**Issue by Rita-Bubnova** [ONLYOFFICE-QA/buguette#987]
I attach the video with a problem.

https://user-images.githubusercontent.com/25282241/172146993-7429fd1b-be63-426b-a0d0-f93bc8ae5ae5.mp4

I use phrase "4. Выделяем оба листа книги следующим образом:" for quick search.

**Comment by ShockwaveNN** [comment]
Seems that this error is raised for any search request with `:` symbol

Like this one:
```
pipa: popa
```

Need to properly escape `:`
